version: '3'

networks:
  playground:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  MyRedisCache:
    image: redis:7.0.14
    container_name: MyRedisCache
    networks:
      playground:
        ipv4_address: 172.18.0.3
    ports:
      - "6380:6379"

  MyPlaygroundDb:
    image: postgres:14.9
    container_name: MyPlaygroundDb
    networks:
      playground:
        ipv4_address: 172.18.0.2
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "3307:5432"

  MyAuthServer:
    image: bluekms/playground-auth-server
    container_name: MyAuthServer
    networks:
      playground:
        ipv4_address: 172.18.0.4
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "5241:80"
      - "7241:443"
    depends_on:
      - MyRedisCache
      - MyPlaygroundDb
