server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs  # TODO promtail이 가져오는 서버의 이름이 되도록 하고싶다
          __path__: /var/log/*log

    # https://grafana.com/docs/loki/latest/send-data/promtail/stages/json/
    pipeline_stages:
      - json:
          expressions:
            Level: "Level"
            RequestPath: "Properties.RequestPath"

      # https://grafana.com/docs/loki/latest/send-data/promtail/stages/labels/
      - labels:
          Level:
          RequestPath:
