# @name Foo2
### OpenApi
POST {{Address}}/Auth/Foo2
Content-Type: application/json

{ "Data": "asdfasdf" }

###

# @name Foo
### After Login
POST {{Address}}/Auth/Foo
Content-Type: application/json
Authorization: Bearer {{SessionId}}

{ "Data": "kkk" }