# @name Foo2_A
POST https://{{host}}:{{port}}/Auth/Foo2
Content-Type: application/json

{ "Data": "asdfasdf" }

###

# @name SignUp
POST https://{{host}}:{{port}}/Auth/SignUp
Content-Type: application/json

{
  "AccountId": "{{username}}",
  "Password": "{{password}}"
}

###

# @name Login
POST https://{{host}}:{{port}}/Auth/Login
Content-Type: application/json

{
  "AccountId": "{{username}}",
  "Password": "{{password}}"
}

> {%
    var responseString = JSON.stringify(response.body, null, 2);
    var responseBody = JSON.parse(responseString);
    client.global.set("SessionId", responseBody.sessionId);
%}

###

# @name Foo
POST https://{{host}}:{{port}}/Auth/Foo
Content-Type: application/json
Authorization: Bearer {{SessionId}}

{ "Data": "kkk" }

###

# @name Foo_Fail
POST https://{{host}}:{{port}}/Auth/Foo
Content-Type: application/json

{ "Data": "kkk2" }