# @name Login
POST {{Address}}/Auth/Login
Content-Type: application/json

{
  "AccountId": "{{username}}",
  "Password": "{{password}}"
}

> {%
    var responseString = JSON.stringify(response.body, null, 2);
    var responseBody = JSON.parse(responseString);
    client.global.set("SessionId", responseBody.sessionId);
%}