name: Deploy Auth Server

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      UseSpecificTag:
        type: boolean
        default: false
        description: latest와 특정 tag를 같이 업로드
    
jobs:
  docker:
    name: AuthServer
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Get Commit ID
        id: commit_id
        run: echo "{COMMIT_ID}={$(git rev-parse --short HEAD)}" >> $GITHUB_OUTPUT

      - name: Build and tag push
        if: ${{ inputs.UseSpecificTag }}
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:${{ steps.commit_id.outputs.COMMIT_ID }}
          
      - name: Build and tag:latest push
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:latest