name: Deploy AuthServer
on:
  workflow_dispatch:
    inputs:
      DockerHubId:
        name: Docker Hub Id
      Password:
        name: Docker Hub Password
    
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DockerHubId }}
          password: ${{ inputs.Password }}
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:${{ github.sha }}
          
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ inputs.DockerHubId }}
            password: ${{ inputs.Password }}
          repository: bluekms/playground-auth-server