name: Deploy AuthServer
on:
  workflow_dispatch:
    inputs:
      name: UseSpecificTag
      type: boolean
      default: false
      description: latest와 함께 sha_short를 추가로 push
    
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and tag:latest push
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:latest
          
      - name: Split Github Sha
        if: ${{ inputs.UseSpecificTag }}
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Build and tag:${{ steps.vars.outputs.sha_short }} push
        if: ${{ inputs.UseSpecificTag }}
        uses: docker/build-push-action@v3
        with:
          file: Servers/AuthServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-auth-server:${{ steps.vars.outputs.sha_short }}