name: Deploy Operation Server

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      UseSpecificTag:
        type: boolean
        default: false
        description: latest와 특정 tag를 같이 업로드
    
jobs:
  docker:
    name: OperationServer
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Split Github Sha
        id: vars
        run: echo "name=sha_short::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Build and tag:${GITHUB_SHA::7} push
        if: ${{ inputs.UseSpecificTag }}
        uses: docker/build-push-action@v3
        with:
          file: Servers/OperationServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-operation-server:${GITHUB_SHA::7}
          
      - name: Build and tag:latest push
        uses: docker/build-push-action@v3
        with:
          file: Servers/OperationServer/Dockerfile
          context: .
          push: true
          tags: bluekms/playground-operation-server:latest