name: Docker Build Test For AuthServer

on:
  workflow_call:

jobs:
  docker:
    name: AuthServer
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: BuildTest
        uses: docker/build-push-action@v3
        with:
          file: AuthServer.Dockerfile
          context: .
          push: false
          tags: bluekms/playground-auth-server:test
