on:
  workflow_call:
    
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3
        
      - name: Formatting
        run: dotnet format --no-restore

      - name: Check spelling
        uses: crate-ci/typos@master