name: CI Root

on:
  push:
    branches: [ "main" ]

jobs:
  Linting:
    uses: ./.github/workflows/ci-lint.yml
  
  Build:
    uses: ./.github/workflows/ci-build.yml
  
  UnitTest:
    needs: [Linting]
    uses: ./.github/workflows/ci-test.yml