name: CI Root

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  spell:
    uses: ./.github/workflows/ci-spell.yaml
  
  build:
    uses: ./.github/workflows/ci-build.yaml  
      
#  test:
#    uses: ./.github/workflows/ci-test.yaml