name: CI Root

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  SpellCheck:
    uses: ./.github/workflows/ci-spell.yml
  
  Build:
    uses: ./.github/workflows/ci-build.yml  
      
  UnitTest:
    uses: ./.github/workflows/ci-test.yml