name: Test
on:
  workflow_dispatch:

jobs:
  list_branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: List Release Branches
      run: |
        branches=$(git for-each-ref --format='%(refname:short)' refs/heads/Release/*)
        echo "Branches below Release path:"
        echo "$branches"
