name: Test
on:
  push:
    branches: ["Release/*"]

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: Message Test
        run: echo "release-" ${{ github.ref }} "-" ${GITHUB_SHA} >> $GITHUB_OUTPUT
