name: Test
on:
  workflow_dispatch:

jobs:
  list_release_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get Last Branch
        run: |
          git fetch --prune --unshallow
          last=$(git branch -r | grep "origin/release" | cut -c 18-23 | sort -rn | head -n1)
          echo "!!!"
          echo "$last"
          echo "!!!"
      - name: Use Last Branch
        run: echo "$last"
