name: Test
on:
  push:
    branches: ["Release/*"]

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Split Github Sha
        id: vars
        run: echo "name=sha_short::$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Message Test
        run: echo "release-${{ github.ref }}-${{ steps.vars.outputs.sha_short }}" >> $GITHUB_OUTPUT
