name: Test
on:
  workflow_dispatch:

jobs:
  retrieve_branch_name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get Release Branch Name
      run: |
        RELEASE_BRANCH=$(git for-each-ref --sort=-committerdate refs/heads/Release* --format='%(refname:short)' | head -n 1)
        echo "The last Release branch name is: $RELEASE_BRANCH"
        
    - name: Save Release Branch Name as Variable
      run: |
        echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV
      
    - name: Output Release Branch Name
      run: |
        echo "The saved Release branch name is: $RELEASE_BRANCH"
