name: Test
on:
  workflow_dispatch:

jobs:
  list_release_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List Branches
        run: |
          git fetch --prune --unshallow
          branches=$(git branch -r | grep "^release" | sort -rn | head -n3)
          echo "!!!"
          echo "$branches"
          echo "!!!"
