name: Test
on:
  push:
    branches: ["Release/*"]

jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Message Test
        run: MESSAGE="release-${{ github.ref.replace('refs/heads/', '') }}-${{ github.sha:0:7 }}"
