name: Test
on:
  workflow_dispatch:

jobs:
  list_release_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: List Branches
        run: |
          git fetch --prune --unshallow
          branches=$(git branch -r --format='%(refname:lstrip=3)')
          echo "$branches"
